name: Build macOS Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build macOS executable
      run: pyinstaller --onefile --icon=icon.ico --name=GPT-anki-helper app.py

    - name: Upload executable
      uses: actions/upload-artifact@v2
      with:
        name: GPT-anki-helper_macos
        path: dist/GPT-anki-helper
